export const EXAMPLE_PATH = 'cms-datocms'
export const CMS_NAME = 'DatoCMS'
export const CMS_URL = 'https://www.datocms.com/'
export const HOME_OG_IMAGE_URL = 'https://www.aupetitventreheureux.fr/_next/image?url=%2Fimages%2Ffacade.jpg&w=1920&q=75'
export const HOME_OG_TITLE = 'Au Petit Ventre Heureux'
export const HOME_OG_URL = 'https://www.aupetitventreheureux.fr'
export const HOME_OG_DESCRIPTION = 'Petite entreprise familiale de restauration rapide, traiteur et rôtisserie . Notre chef, au quotidien, axe son travail sur la créativité et l’originalité.'
